version: '3'
services:
  app-test:
    build: .
    container_name: app-test
    volumes:
      - .:/var/www/app
      - ./build-deploy/nginx/ssl:/etc/nginx/ssl
      - ./build-deploy/nginx/domains.d:/etc/nginx/domains.d
      - ./build-deploy/nginx/serve.d:/etc/nginx/serve.d
    env_file: .env
    command: build-deploy/test.sh
    depends_on:
      - mysql-test
      - redis-test
    links:
      - mysql-test
      - redis-test
    networks:
      app-test:
        aliases:
          - app.local
    ports:
      - "80:80"
      - "443:443"
  mysql-test:
    image: percona:5.7
    env_file: .env
    networks:
      app-test:
        aliases:
          - mysql.app.local
    ports:
      - "3306:3306"
  redis:
    image: redis:3.2
    networks:
      app-test:
        aliases:
          - redis.app.local
    ports:
      - "6379:6379"
networks:
  app-test: