version: '3'
services:
  app-test:
    build: .
    container_name: app-test
    volumes:
      - .:/var/www/app
      - ./build-deploy/nginx/ssl:/etc/nginx/ssl
      - ./build-deploy/nginx/domains.d:/etc/nginx/domains.d
    env_file: .env
    command: build-deploy/test.sh
    depends_on:
      - mysql-test
      - redis-test
    links:
      - mysql-test
      - redis-test
    networks:
      app-test:
        aliases:
          - app.local
  mysql-test:
    image: percona:5.7
    env_file: .env
    networks:
      app-test:
        aliases:
          - mysql.app.local
  redis-test:
    image: redis:3.2
    networks:
      app-test:
        aliases:
          - redis.app.local
networks:
  app-test: