version: '3'
services:
  app:
    build: .
    volumes:
      - .:/var/www/app
      - /var/www/app/vendor
      - ./build-deploy/nginx/ssl:/etc/nginx/ssl
      - ./build-deploy/nginx/domains.d:/etc/nginx/domains.d
    env_file: .env
    command: build-deploy/run.sh
    depends_on:
      - mysql
      - redis
    networks:
      app:
        aliases:
          - app.local
    ports:
      - "80:80"
      - "443:443"
  mysql:
    image: percona:latest
    env_file: .env
    networks:
      app:
        aliases:
          - mysql.app.local
    ports:
      - "3306:3306"
  redis:
    image: redis:latest
    networks:
      app:
        aliases:
          - redis.app.local
    ports:
      - "6379:6379"
networks:
  app:
