version: '3'
services:
  app:
    build: .
    container_name: app
    volumes:
      - .:/var/www/app
      - ./build-deploy/nginx/app.conf:/etc/nginx/conf.d/app.conf
    env_file: .env
    command: build-deploy/dev.sh
    depends_on:
      - mysql
      - redis
    links:
      - mysql
      - redis
    networks:
      app:
        aliases:
          - app.local
    ports:
      - "80:80"
      - "443:443"
  mysql:
    image: percona:5.7
    env_file: .env
    networks:
      app:
        aliases:
          - mysql.app.local
    ports:
      - "3306:3306"
  redis:
    image: redis:3.2
    networks:
      app:
        aliases:
          - redis.app.local
networks:
  app: