#!/usr/bin/env php
<?php

/** @var \App\Application $app */
$app = require __DIR__ . '/app.php';

$status = $app->run(function(\App\Console\ConsoleKernel $kernel) {
    return $kernel->run();
});

exit($status);
