#!/usr/bin/env php
<?php

require __DIR__ . '/bootstrap/app.php';

try {
    $status = app()->run(function(\App\Console\ConsoleKernel $kernel) {
        return $kernel->run();
    });

    exit($status);
} catch (Exception $e) {
    \Greg\Support\Http\Response::sendCode(500);

    dump($e->getMessage(), $e->getTraceAsString());
}
